### ISSUE TITLE
Radio button validation issue

### ISSUE THREAD

**Issue by palashmon** [AntonLapshin/popup-validation#1]
Just wanted share some thought on my initial testing for this repo.

In the [demo](https://antonlapshin.github.io/popup-validation/) page for `Gender` radio button validation, I see that **required** is showing for both _male_ & _female_ options, which is correct. But, once I select either of the one option like _male_, the _female_ radio button still shows as **required**, which I think is not correct as we can only select one option if multiple radio buttons have same `name` attribute (in this case they have same `name` attribute `gender`). Hence, if _male_ radio option is already selected this means that we don't have any validation issue anymore for the `Gender` field.

![git-issue-001](https://user-images.githubusercontent.com/14850464/28631958-983a49d2-724c-11e7-8841-a69b64777179.jpg)

So, ideal situation would have been once I clicked _male_ radio button, the **required** popup would automatically be removed from _female_ radio button also. In general, if any of the options in a radio button group is selected remove required popup from that section.

Regards!

**Comment by AntonLapshin** [comment]
@palashmon Hi Palash,

You are absolutely right. I will fix that when I get a chance.

Thank you for your good catch.
Anton

**Comment by palashmon** [comment]
My pleasure. I will let you know if I find any more issues.

At moment, you can close this issue as it is fixed in commit 6d1fcba.

Also, you could have auto closed this issue using [keyword](https://help.github.com/articles/closing-issues-using-keywords/) in commit message.

Regards!

**Comment by AntonLapshin** [comment]
@palashmon Hi Palash, OK, thank you.

**Comment by palashmon** [comment]
You're welcome :smiley:
